### ISSUE TITLE
웹에서 한글이 입력이 안되는 문제!

### ISSUE THREAD

**Issue by rockpell** [mimseong/Surviving_in_42#103]
현재 사용하는 유니티에서 웹으로 빌드하면 한글 입력이 안되네요

별도의 처리가 필요할 거 같은데 영어로만 이름 입력이 가능하다는 문구가 필요할지도 모르겠네요

입력 제한 글자수도 바꾸고요

**Comment by blingblin-g** [comment]
글자수는 바꿨는데 한글입력은 어쩔 수가 없네요...
그냥 씁시다
