### ISSUE TITLE
피자 장면 고양이 옷

### ISSUE THREAD

**Issue by rockpell** [mimseong/Surviving_in_42#74]
피자 먹는 이벤트 씬에서 고양이가 옷을 안입고 있네요

옷을 입혀주세요 ㅋㅋ

**Comment by mimseong** [comment]
앗ㅋㅋㅋ 전에 나왔던 문제였는데 아직 해결을 못했네요.
바로 수정하겠습니다!

**Comment by mimseong** [comment]
수정했습니다!
