### ISSUE TITLE
BSQ, RUSH의 팀원 이미지 크기 수정

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#77]
BSQ, RUSH 씬 중 팀원 소개하는 씬에 고양이 얼굴이 너무 큽니다ㅠㅠ

조금 줄이면 좋을 것 같습니다!

**Comment by blingblin-g** [comment]
![비교해보세요](https://user-images.githubusercontent.com/60090391/81159062-8de1c680-8fc3-11ea-9ffd-f6751f7fe753.PNG)


어떤가요?

**Comment by mimseong** [comment]
오오 좋아요~~! 액자는 없는 게 좋을 것 같네요
