### ISSUE TITLE
이름 등록 시 버튼 활성화 이슈

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#81]
![image](https://user-images.githubusercontent.com/50068946/81393244-fca55800-915a-11ea-839a-b59ef0a17f69.png)

이름을 등록한 다음 **등록되었습니다!** 문구가 뜰 때 버튼을 비활성화 하는 건 어떨까요?

실수로 버튼을 눌러 레벨을 못 보고 지나칠 수 있을 것 같습니다!

**Comment by blingblin-g** [comment]
해결했습니다!
