### ISSUE TITLE
버튼 사라지는 버그 발견했습니다

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#82]
![image](https://user-images.githubusercontent.com/50068946/81393503-72112880-915b-11ea-938f-068e1fb00ce8.png)

ㅠㅠ 첫 날 시작하자마자 **?(도움말)** 버튼을 눌렀는데, 문구가 끝나고 난 뒤 할일 버튼이 사라져있습니다

**Comment by blingblin-g** [comment]
텍스트 크기가 이상했네요. 원인은 모르겠지만 수정했습니다!
