### ISSUE TITLE
시험 가기 전 버그 찾았습니다

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#87]
시험 전날에 피로가 누적되어 집에 가는 상황인데,

강제로 집에 가기 전에 앗!!! 하는 장면이 뜨고 시험 이미지로 바뀝니다..

2주의 스타워즈 배경 이미지로 바뀌는 부분입니다.

**Comment by blingblin-g** [comment]
![exam bug](https://user-images.githubusercontent.com/60090391/81414201-92ec7480-9181-11ea-8b15-f6bd56efce95.PNG)

이부분인거죠

**Comment by mimseong** [comment]
> ![exam bug](https://user-images.githubusercontent.com/60090391/81414201-92ec7480-9181-11ea-8b15-f6bd56efce95.PNG)
> 
> 이부분인거죠

맞아요!! 이 장면이 뜨고 시험을 치러 가서 조금 어색합니다

**Comment by blingblin-g** [comment]
해결!
