### ISSUE TITLE
BSQ의 얼굴 크기 수정이 안 됐어요!

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#88]
![image](https://user-images.githubusercontent.com/50068946/81413702-d72b4500-9180-11ea-9dd6-a264c1648905.png)

RUSH는 수정이 됐는데 여긴 아직 찐빵이네요ㅠㅠ 

크기 조정 부탁드립니다!

**Comment by blingblin-g** [comment]
수정했습니다
