### ISSUE TITLE
게임 엔딩 이후 다시 시작할 때 초기화가 안 되어있습니다!

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#90]
![image](https://user-images.githubusercontent.com/50068946/81414447-f9719280-9181-11ea-9089-e9b940c7dcb6.png)

- 스테이터스
- 날짜
- 42레벨

이 세가지 값 초기화가 필요해요!

그리고 브금도 바뀌지 않았습니다.

**Comment by blingblin-g** [comment]
했습니당
