### ISSUE TITLE
컨닝하기 이미지 띄우기 이슈

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#97]
![image](https://user-images.githubusercontent.com/50068946/81472987-ab6a9680-9236-11ea-8d25-fc633c504c48.png)

컨닝하기를 할 때 처음에 플레이어 이미지가 없다가 나중에 나오는데 

![cheating_player](https://user-images.githubusercontent.com/50068946/81473007-d654ea80-9236-11ea-84bd-c30590567c3a.png)

컨닝 결과에 상관없이 이 이미지를 사용하고 컨닝하기 들켰을 때 부끄러워 하는 이미지를 적용시키는 건 어떨까요?

**Comment by blingblin-g** [comment]
해결!
