### ISSUE TITLE
행복한 돼지 엔딩이 너무 자주 나와요!!

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#98]
빈둥대기 엔딩을 보려고 엄청 빈둥대고 
노숙자 엔딩 보려고 엄청 많이 잤는데 둘 다 행복한 돼지가 나오네요ㅠㅠ
아카데미 안에 자주 있으면 쉽게 받을 수 있는 엔딩 인 것 같아요.
우선순위를 낮춰야 할 필요가 있습니다.

**Comment by blingblin-g** [comment]
바꿨습니당
