### ISSUE TITLE
[코딩 마스터 칭호] 조건 상향 조절 필요합니다

### ISSUE THREAD

**Issue by mimseong** [mimseong/Surviving_in_42#99]
![image](https://user-images.githubusercontent.com/50068946/81474631-c393e300-9241-11ea-80a1-685617afbc84.png)

3주차 수요일에 이미 만렙을 찍었습니다.
BSQ와 시험으로 코딩 레벨이 오를 것을 감안하면 만렙 찍기가 어렵지 않을 것 같으니
칭호 조건을 42일 때 얻게 하면 좋을 것 같습니다.

**Comment by blingblin-g** [comment]
해결!
